version: "3"
services:
  db:
    image: mysql
    container_name: demo-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test

  app:
    image: demo-fastapi
    container_name: demo-app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - API_VERSION=${API_VERSION}
      - ENV=${ENV}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db


